module.exports = {
    apps: [
        {
            name: 'prakasa-qwen3-0.6b',
            script: '/root/code/prakasa/venv/bin/prakasa',
            args: 'run --config config-1.yaml',
            interpreter: 'none',
            cwd: '/root/code/prakasa',
            env: {
                NODE_ENV: 'production',
            },
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '2G',
            error_file: './logs/prakasa-qwen3-0.6b-err.log',
            out_file: './logs/prakasa-qwen3-0.6b-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
        {
            name: 'prakasa-qwen2.5-7b',
            script: '/root/code/prakasa/venv/bin/prakasa',
            args: 'run --config config-2.yaml',
            interpreter: 'none',
            cwd: '/root/code/prakasa',
            env: {
                NODE_ENV: 'production',
            },
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '2G',
            error_file: './logs/prakasa-qwen2.5-7b-err.log',
            out_file: './logs/prakasa-qwen2.5-7b-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
        {
            name: 'prakasa-deepseek-v3.2',
            script: '/root/code/prakasa/venv/bin/prakasa',
            args: 'run --config config-3.yaml',
            interpreter: 'none',
            cwd: '/root/code/prakasa',
            env: {
                NODE_ENV: 'production',
            },
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '2G',
            error_file: './logs/prakasa-deepseek-v3.2-err.log',
            out_file: './logs/prakasa-deepseek-v3.2-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
        {
            name: 'prakasa-llama-3.1-8b',
            script: '/root/code/prakasa/venv/bin/prakasa',
            args: 'run --config config-4.yaml',
            interpreter: 'none',
            cwd: '/root/code/prakasa',
            env: {
                NODE_ENV: 'production',
            },
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '2G',
            error_file: './logs/prakasa-llama-3.1-8b-err.log',
            out_file: './logs/prakasa-llama-3.1-8b-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
        {
            name: 'prakasa-llama-3.3-70b',
            script: '/root/code/prakasa/venv/bin/prakasa',
            args: 'run --config config-5.yaml',
            interpreter: 'none',
            cwd: '/root/code/prakasa',
            env: {
                NODE_ENV: 'production',
            },
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '2G',
            error_file: './logs/prakasa-llama-3.3-70b-err.log',
            out_file: './logs/prakasa-llama-3.3-70b-out.log',
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
        },
    ],
};
